//
// CartCatalogPriceRulesCount200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CartCatalogPriceRulesCount200ResponseResult: Sendable, Codable, JSONEncodable, Hashable {

    public var catalogPriceRulesCount: Int?

    public init(catalogPriceRulesCount: Int? = nil) {
        self.catalogPriceRulesCount = catalogPriceRulesCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case catalogPriceRulesCount = "catalog_price_rules_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(catalogPriceRulesCount, forKey: .catalogPriceRulesCount)
    }
}

