//
// CartScriptAdd200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CartScriptAdd200ResponseResult: Sendable, Codable, JSONEncodable, Hashable {

    public var scriptId: String?

    public init(scriptId: String? = nil) {
        self.scriptId = scriptId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case scriptId = "script_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(scriptId, forKey: .scriptId)
    }
}

