//
// CartBridge200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CartBridge200ResponseResult: Sendable, Codable, JSONEncodable, Hashable {

    public var storeKey: String?
    public var bridge: String?

    public init(storeKey: String? = nil, bridge: String? = nil) {
        self.storeKey = storeKey
        self.bridge = bridge
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case storeKey = "store_key"
        case bridge
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(storeKey, forKey: .storeKey)
        try container.encodeIfPresent(bridge, forKey: .bridge)
    }
}

