//
// CartDelete200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CartDelete200ResponseResult: Sendable, Codable, JSONEncodable, Hashable {

    public var store: String?

    public init(store: String? = nil) {
        self.store = store
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case store
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(store, forKey: .store)
    }
}

