//
// CustomerGroupAdd200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CustomerGroupAdd200ResponseResult: Sendable, Codable, JSONEncodable, Hashable {

    public var groupId: String?

    public init(groupId: String? = nil) {
        self.groupId = groupId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groupId = "group_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(groupId, forKey: .groupId)
    }
}

