//
// CustomerAdd200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CustomerAdd200ResponseResult: Sendable, Codable, JSONEncodable, Hashable {

    public var customerId: String?

    public init(customerId: String? = nil) {
        self.customerId = customerId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customerId = "customer_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customerId, forKey: .customerId)
    }
}

