//
// OrderFulfillmentStatusList200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OrderFulfillmentStatusList200ResponseResult: Sendable, Codable, JSONEncodable, Hashable {

    public var orderFulfillmentStatuses: [OrderFinancialStatusList200ResponseResultOrderFinancialStatusesInner]?

    public init(orderFulfillmentStatuses: [OrderFinancialStatusList200ResponseResultOrderFinancialStatusesInner]? = nil) {
        self.orderFulfillmentStatuses = orderFulfillmentStatuses
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderFulfillmentStatuses = "order_fulfillment_statuses"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(orderFulfillmentStatuses, forKey: .orderFulfillmentStatuses)
    }
}

