//
// OrderReturnAdd200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OrderReturnAdd200ResponseResult: Sendable, Codable, JSONEncodable, Hashable {

    public var returnId: String?

    public init(returnId: String? = nil) {
        self.returnId = returnId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case returnId = "return_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(returnId, forKey: .returnId)
    }
}

