//
// ParamDefinitionFilteringConditionsFilterGroup.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ParamDefinitionFilteringConditionsFilterGroup: Sendable, Codable, JSONEncodable, Hashable {

    public var and: [JSONValue]?
    public var or: [JSONValue]?
    public var not: JSONValue?

    public init(and: [JSONValue]? = nil, or: [JSONValue]? = nil, not: JSONValue? = nil) {
        self.and = and
        self.or = or
        self.not = not
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case and
        case or
        case not
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(and, forKey: .and)
        try container.encodeIfPresent(or, forKey: .or)
        try container.encodeIfPresent(not, forKey: .not)
    }
}

