//
// ParamDefinitionFilteringConditionsFilterCondition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ParamDefinitionFilteringConditionsFilterCondition: Sendable, Codable, JSONEncodable, Hashable {
    case typeParamDefinitionFilteringConditionsFilterGroup(ParamDefinitionFilteringConditionsFilterGroup)
    case typeParamDefinitionFilteringConditionsFilterRule(ParamDefinitionFilteringConditionsFilterRule)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeParamDefinitionFilteringConditionsFilterGroup(let value):
            try container.encode(value)
        case .typeParamDefinitionFilteringConditionsFilterRule(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(ParamDefinitionFilteringConditionsFilterGroup.self) {
            self = .typeParamDefinitionFilteringConditionsFilterGroup(value)
        } else if let value = try? container.decode(ParamDefinitionFilteringConditionsFilterRule.self) {
            self = .typeParamDefinitionFilteringConditionsFilterRule(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of ParamDefinitionFilteringConditionsFilterCondition"))
        }
    }
}

