//
// PluginList.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PluginList: Sendable, Codable, JSONEncodable, Hashable {

    public var allPlugins: Int?
    public var plugins: [Plugin]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(allPlugins: Int? = nil, plugins: [Plugin]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.allPlugins = allPlugins
        self.plugins = plugins
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allPlugins = "all_plugins"
        case plugins
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allPlugins, forKey: .allPlugins)
        try container.encodeIfPresent(plugins, forKey: .plugins)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

