//
// ProductChildItemCombination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProductChildItemCombination: Sendable, Codable, JSONEncodable, Hashable {

    public var optionId: String?
    public var optionValueId: String?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(optionId: String? = nil, optionValueId: String? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.optionId = optionId
        self.optionValueId = optionValueId
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case optionId = "option_id"
        case optionValueId = "option_value_id"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(optionId, forKey: .optionId)
        try container.encodeIfPresent(optionValueId, forKey: .optionValueId)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

