//
// ProductAdd200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ProductAdd200ResponseResult: Sendable, Codable, JSONEncodable, Hashable {

    public var productId: String?

    public init(productId: String? = nil) {
        self.productId = productId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case productId = "product_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(productId, forKey: .productId)
    }
}

