//
// ResponseAttributeListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseAttributeListResult: Sendable, Codable, JSONEncodable, Hashable {

    public var attributesCount: Int?
    public var attribute: [StoreAttribute]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(attributesCount: Int? = nil, attribute: [StoreAttribute]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.attributesCount = attributesCount
        self.attribute = attribute
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attributesCount = "attributes_count"
        case attribute
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attributesCount, forKey: .attributesCount)
        try container.encodeIfPresent(attribute, forKey: .attribute)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

