//
// ResponseCartCouponCountResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseCartCouponCountResult: Sendable, Codable, JSONEncodable, Hashable {

    public var couponsCount: Int?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(couponsCount: Int? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.couponsCount = couponsCount
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case couponsCount = "coupons_count"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(couponsCount, forKey: .couponsCount)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

