//
// ResponseReturnReasonListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseReturnReasonListResult: Sendable, Codable, JSONEncodable, Hashable {

    public var returnReasons: [Status]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(returnReasons: [Status]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.returnReasons = returnReasons
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case returnReasons = "return_reasons"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(returnReasons, forKey: .returnReasons)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

