//
// ResponseCartShippingZonesListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseCartShippingZonesListResult: Sendable, Codable, JSONEncodable, Hashable {

    public var shippingZone: [CartShippingZone2]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(shippingZone: [CartShippingZone2]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.shippingZone = shippingZone
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shippingZone = "shipping_zone"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(shippingZone, forKey: .shippingZone)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

