//
// ResponseCategoryListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseCategoryListResult: Sendable, Codable, JSONEncodable, Hashable {

    public var categoriesCount: Int?
    public var category: [Category]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(categoriesCount: Int? = nil, category: [Category]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.categoriesCount = categoriesCount
        self.category = category
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoriesCount = "categories_count"
        case category
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categoriesCount, forKey: .categoriesCount)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

