//
// ResponseCustomerListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseCustomerListResult: Sendable, Codable, JSONEncodable, Hashable {

    public var customersCount: Int?
    public var customer: [Customer]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(customersCount: Int? = nil, customer: [Customer]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.customersCount = customersCount
        self.customer = customer
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customersCount = "customers_count"
        case customer
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customersCount, forKey: .customersCount)
        try container.encodeIfPresent(customer, forKey: .customer)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

