//
// ResponseReturnActionListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseReturnActionListResult: Sendable, Codable, JSONEncodable, Hashable {

    public var returnActions: [Status]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(returnActions: [Status]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.returnActions = returnActions
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case returnActions = "return_actions"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(returnActions, forKey: .returnActions)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

