//
// ResponseCartMethodsResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseCartMethodsResult: Sendable, Codable, JSONEncodable, Hashable {

    public var method: [String]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(method: [String]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.method = method
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case method
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(method, forKey: .method)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

