//
// ResponseCustomerGroupListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseCustomerGroupListResult: Sendable, Codable, JSONEncodable, Hashable {

    public var groupCount: Int?
    public var group: [CustomerGroup]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(groupCount: Int? = nil, group: [CustomerGroup]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.groupCount = groupCount
        self.group = group
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groupCount = "group_count"
        case group
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(groupCount, forKey: .groupCount)
        try container.encodeIfPresent(group, forKey: .group)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

