//
// ResponseProductChildItemFindResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseProductChildItemFindResult: Sendable, Codable, JSONEncodable, Hashable {

    public var children: [Child]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(children: [Child]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.children = children
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case children
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(children, forKey: .children)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

