//
// ResponseMarketplaceProductFindResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseMarketplaceProductFindResult: Sendable, Codable, JSONEncodable, Hashable {

    public var marketplaceProductsCount: Int?
    public var marketplaceProduct: [MarketplaceProduct]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(marketplaceProductsCount: Int? = nil, marketplaceProduct: [MarketplaceProduct]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.marketplaceProductsCount = marketplaceProductsCount
        self.marketplaceProduct = marketplaceProduct
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case marketplaceProductsCount = "marketplace_products_count"
        case marketplaceProduct = "marketplace_product"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(marketplaceProductsCount, forKey: .marketplaceProductsCount)
        try container.encodeIfPresent(marketplaceProduct, forKey: .marketplaceProduct)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

