//
// ResponseWebhookCountResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseWebhookCountResult: Sendable, Codable, JSONEncodable, Hashable {

    public var webhookCount: Int?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(webhookCount: Int? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.webhookCount = webhookCount
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case webhookCount = "webhook_count"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(webhookCount, forKey: .webhookCount)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

