//
// ResponseWebhookEventsResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseWebhookEventsResult: Sendable, Codable, JSONEncodable, Hashable {

    public var events: [WebhookEvent]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(events: [WebhookEvent]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.events = events
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case events
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(events, forKey: .events)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

