//
// ResponseReturnStatusListResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ResponseReturnStatusListResult: Sendable, Codable, JSONEncodable, Hashable {

    public var returnStatuses: [Status]?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(returnStatuses: [Status]? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.returnStatuses = returnStatuses
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case returnStatuses = "return_statuses"
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(returnStatuses, forKey: .returnStatuses)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

