//
// ReturnActionList200ResponseResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReturnActionList200ResponseResult: Sendable, Codable, JSONEncodable, Hashable {

    public var returnActions: [OrderFinancialStatusList200ResponseResultOrderFinancialStatusesInner]?

    public init(returnActions: [OrderFinancialStatusList200ResponseResultOrderFinancialStatusesInner]? = nil) {
        self.returnActions = returnActions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case returnActions = "return_actions"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(returnActions, forKey: .returnActions)
    }
}

