//
// State.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct State: Sendable, Codable, JSONEncodable, Hashable {

    public var code: String?
    public var name: String?
    public var additionalFields: JSONValue?
    public var customFields: JSONValue?

    public init(code: String? = nil, name: String? = nil, additionalFields: JSONValue? = nil, customFields: JSONValue? = nil) {
        self.code = code
        self.name = name
        self.additionalFields = additionalFields
        self.customFields = customFields
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case name
        case additionalFields = "additional_fields"
        case customFields = "custom_fields"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(code, forKey: .code)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(additionalFields, forKey: .additionalFields)
        try container.encodeIfPresent(customFields, forKey: .customFields)
    }
}

