//
// AnalyticsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AnalyticsAPI {

    /**
     analytics.customer_report
     
     - parameter dateFrom: (query) Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     - parameter dateTo: (query) End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     - parameter count: (query) This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     - parameter currencyId: (query) Currency Id (optional)
     - parameter storeId: (query) Store Id (optional)
     - parameter customerType: (query) Filter analytics customers by customer type (optional)
     - parameter email: (query) Filter analytics customers by email (optional)
     - parameter sortBy: (query) Set field to sort by (optional, default to "total_spend")
     - parameter sortDirection: (query) Set sorting direction (optional, default to "desc")
     - parameter pageCursor: (query) Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     - parameter responseFields: (query) Set this parameter in order to choose which entity fields you want to retrieve (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ResponseAnalyticsCustomerReportResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func analyticsCustomerReport(dateFrom: String? = nil, dateTo: String? = nil, count: Int? = nil, currencyId: String? = nil, storeId: String? = nil, customerType: String? = nil, email: String? = nil, sortBy: String? = nil, sortDirection: String? = nil, pageCursor: String? = nil, responseFields: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ResponseAnalyticsCustomerReportResult {
        return try await analyticsCustomerReportWithRequestBuilder(dateFrom: dateFrom, dateTo: dateTo, count: count, currencyId: currencyId, storeId: storeId, customerType: customerType, email: email, sortBy: sortBy, sortDirection: sortDirection, pageCursor: pageCursor, responseFields: responseFields, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     analytics.customer_report
     - GET /analytics.customer_report.json
     - Get customer-level analytics for a store over a given period.
     - API Key:
       - type: apiKey x-store-key (HEADER)
       - name: StoreKeyAuth
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: ApiKeyAuth
     - parameter dateFrom: (query) Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     - parameter dateTo: (query) End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     - parameter count: (query) This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     - parameter currencyId: (query) Currency Id (optional)
     - parameter storeId: (query) Store Id (optional)
     - parameter customerType: (query) Filter analytics customers by customer type (optional)
     - parameter email: (query) Filter analytics customers by email (optional)
     - parameter sortBy: (query) Set field to sort by (optional, default to "total_spend")
     - parameter sortDirection: (query) Set sorting direction (optional, default to "desc")
     - parameter pageCursor: (query) Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     - parameter responseFields: (query) Set this parameter in order to choose which entity fields you want to retrieve (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ResponseAnalyticsCustomerReportResult> 
     */
    open class func analyticsCustomerReportWithRequestBuilder(dateFrom: String? = nil, dateTo: String? = nil, count: Int? = nil, currencyId: String? = nil, storeId: String? = nil, customerType: String? = nil, email: String? = nil, sortBy: String? = nil, sortDirection: String? = nil, pageCursor: String? = nil, responseFields: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ResponseAnalyticsCustomerReportResult> {
        let localVariablePath = "/analytics.customer_report.json"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "date_from": (wrappedValue: dateFrom?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "date_to": (wrappedValue: dateTo?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "currency_id": (wrappedValue: currencyId?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "store_id": (wrappedValue: storeId?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "customer_type": (wrappedValue: customerType?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "email": (wrappedValue: email?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort_by": (wrappedValue: sortBy?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort_direction": (wrappedValue: sortDirection?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page_cursor": (wrappedValue: pageCursor?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "response_fields": (wrappedValue: responseFields?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ResponseAnalyticsCustomerReportResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     analytics.product_report
     
     - parameter dateFrom: (query) Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     - parameter dateTo: (query) End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     - parameter count: (query) This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     - parameter productIds: (query) Filter analytics by product ids (optional)
     - parameter currencyId: (query) Currency Id (optional)
     - parameter storeId: (query) Store Id (optional)
     - parameter categoriesIds: (query) Defines product add that is specified by comma-separated categories id (optional)
     - parameter sortBy: (query) Set field to sort by (optional, default to "items_sold")
     - parameter sortDirection: (query) Set sorting direction (optional, default to "desc")
     - parameter pageCursor: (query) Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     - parameter responseFields: (query) Set this parameter in order to choose which entity fields you want to retrieve (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ResponseAnalyticsProductReportResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func analyticsProductReport(dateFrom: String? = nil, dateTo: String? = nil, count: Int? = nil, productIds: String? = nil, currencyId: String? = nil, storeId: String? = nil, categoriesIds: String? = nil, sortBy: String? = nil, sortDirection: String? = nil, pageCursor: String? = nil, responseFields: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ResponseAnalyticsProductReportResult {
        return try await analyticsProductReportWithRequestBuilder(dateFrom: dateFrom, dateTo: dateTo, count: count, productIds: productIds, currencyId: currencyId, storeId: storeId, categoriesIds: categoriesIds, sortBy: sortBy, sortDirection: sortDirection, pageCursor: pageCursor, responseFields: responseFields, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     analytics.product_report
     - GET /analytics.product_report.json
     - Get product-level analytics for a store over a given period.
     - API Key:
       - type: apiKey x-store-key (HEADER)
       - name: StoreKeyAuth
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: ApiKeyAuth
     - parameter dateFrom: (query) Start date for the analytics period (Y-m-d or Y-m-d H:i:s) (optional)
     - parameter dateTo: (query) End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     - parameter count: (query) This parameter sets the entity amount that has to be retrieved. Max allowed count&#x3D;250 (optional, default to 10)
     - parameter productIds: (query) Filter analytics by product ids (optional)
     - parameter currencyId: (query) Currency Id (optional)
     - parameter storeId: (query) Store Id (optional)
     - parameter categoriesIds: (query) Defines product add that is specified by comma-separated categories id (optional)
     - parameter sortBy: (query) Set field to sort by (optional, default to "items_sold")
     - parameter sortDirection: (query) Set sorting direction (optional, default to "desc")
     - parameter pageCursor: (query) Used to retrieve entities via cursor-based pagination (it can&#39;t be used with any other filtering parameter) (optional)
     - parameter responseFields: (query) Set this parameter in order to choose which entity fields you want to retrieve (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ResponseAnalyticsProductReportResult> 
     */
    open class func analyticsProductReportWithRequestBuilder(dateFrom: String? = nil, dateTo: String? = nil, count: Int? = nil, productIds: String? = nil, currencyId: String? = nil, storeId: String? = nil, categoriesIds: String? = nil, sortBy: String? = nil, sortDirection: String? = nil, pageCursor: String? = nil, responseFields: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ResponseAnalyticsProductReportResult> {
        let localVariablePath = "/analytics.product_report.json"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "date_from": (wrappedValue: dateFrom?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "date_to": (wrappedValue: dateTo?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "count": (wrappedValue: count?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "product_ids": (wrappedValue: productIds?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "currency_id": (wrappedValue: currencyId?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "store_id": (wrappedValue: storeId?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "categories_ids": (wrappedValue: categoriesIds?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort_by": (wrappedValue: sortBy?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort_direction": (wrappedValue: sortDirection?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page_cursor": (wrappedValue: pageCursor?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "response_fields": (wrappedValue: responseFields?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ResponseAnalyticsProductReportResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     analytics.report
     
     - parameter dateFrom: (query) Start date for the analytics period (Y-m-d or Y-m-d H:i:s) 
     - parameter dateTo: (query) End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     - parameter interval: (query) Interval for analytics report breakdown (optional)
     - parameter orderStatus: (query) Retrieves orders specified by order status (optional)
     - parameter financialStatus: (query) Retrieves orders specified by financial status (optional)
     - parameter currencyId: (query) Currency Id (optional)
     - parameter storeId: (query) Store Id (optional)
     - parameter sortBy: (query) Set field to sort by (optional, default to "date")
     - parameter sortDirection: (query) Set sorting direction (optional, default to "asc")
     - parameter responseFields: (query) Set this parameter in order to choose which entity fields you want to retrieve (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ResponseAnalyticsReportResult
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func analyticsReport(dateFrom: String, dateTo: String? = nil, interval: String? = nil, orderStatus: String? = nil, financialStatus: String? = nil, currencyId: String? = nil, storeId: String? = nil, sortBy: String? = nil, sortDirection: String? = nil, responseFields: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ResponseAnalyticsReportResult {
        return try await analyticsReportWithRequestBuilder(dateFrom: dateFrom, dateTo: dateTo, interval: interval, orderStatus: orderStatus, financialStatus: financialStatus, currencyId: currencyId, storeId: storeId, sortBy: sortBy, sortDirection: sortDirection, responseFields: responseFields, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     analytics.report
     - GET /analytics.report.json
     - Get analytics report with totals and optional interval breakdown for a store over a given period.
     - API Key:
       - type: apiKey x-store-key (HEADER)
       - name: StoreKeyAuth
     - API Key:
       - type: apiKey x-api-key (HEADER)
       - name: ApiKeyAuth
     - parameter dateFrom: (query) Start date for the analytics period (Y-m-d or Y-m-d H:i:s) 
     - parameter dateTo: (query) End date for the analytics period (Y-m-d or Y-m-d H:i:s). Defaults to the current date. (optional)
     - parameter interval: (query) Interval for analytics report breakdown (optional)
     - parameter orderStatus: (query) Retrieves orders specified by order status (optional)
     - parameter financialStatus: (query) Retrieves orders specified by financial status (optional)
     - parameter currencyId: (query) Currency Id (optional)
     - parameter storeId: (query) Store Id (optional)
     - parameter sortBy: (query) Set field to sort by (optional, default to "date")
     - parameter sortDirection: (query) Set sorting direction (optional, default to "asc")
     - parameter responseFields: (query) Set this parameter in order to choose which entity fields you want to retrieve (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ResponseAnalyticsReportResult> 
     */
    open class func analyticsReportWithRequestBuilder(dateFrom: String, dateTo: String? = nil, interval: String? = nil, orderStatus: String? = nil, financialStatus: String? = nil, currencyId: String? = nil, storeId: String? = nil, sortBy: String? = nil, sortDirection: String? = nil, responseFields: String? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ResponseAnalyticsReportResult> {
        let localVariablePath = "/analytics.report.json"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "date_from": (wrappedValue: dateFrom.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "date_to": (wrappedValue: dateTo?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "interval": (wrappedValue: interval?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "order_status": (wrappedValue: orderStatus?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "financial_status": (wrappedValue: financialStatus?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "currency_id": (wrappedValue: currencyId?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "store_id": (wrappedValue: storeId?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort_by": (wrappedValue: sortBy?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "sort_direction": (wrappedValue: sortDirection?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "response_fields": (wrappedValue: responseFields?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ResponseAnalyticsReportResult>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
