name: Update swift6-sdk SDK

on:
  # Запускатися раз на тиждень (у неділю о 00:00 за UTC)
  schedule:
    - cron: '0 0 * * 0'
  # Додатково, щоб мати можливість запустити вручну
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_swift6_sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download swift6.tgz
        run: |
          curl -L -o swift6.tgz https://app.api2cart.com/sdk/openapi/swift6.tgz

      # Розпаковуємо, видаляючи 1 рівень (папку swift6)
      - name: Extract swift6.tgz
        run: |
          tar -xzf swift6.tgz --strip-components=1

      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update swift6 SDK [skip ci]"
          git push
